import { type Metadata } from "next";
import { dark } from "@clerk/themes";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});
import { ThemeProvider } from "@/components/theme-provider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      afterSignOutUrl="/"
    >
      <html lang="en"
      >
        <body className={inter.className}>
          <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="gamehun-theme"
          >
            {children}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
